[tool.black]
target_version = [ 'py39' ]

[tool.isort]
py_version = 36
profile = "black"
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
line_length = 100
lines_between_types = 1
src_paths = [ "kubesae", "tests" ]
